In [81]:
import numpy as np

In [82]:
import pandas as pd

In [83]:
mylist=[1,2,3]
mylist

[1, 2, 3]

In [84]:
np.array(mylist)

array([1, 2, 3])

In [85]:
my_matrix=[[1,2,3],[4,8,5],[34,53,23]]
my_matrix
np.array(my_matrix)

array([[ 1,  2,  3],
       [ 4,  8,  5],
       [34, 53, 23]])

In [86]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [87]:
np.zeros(3)

array([0., 0., 0.])

In [88]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [89]:
np.ones(3)

array([1., 1., 1.])

In [90]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [91]:
np.random.rand(2)

array([0.26797157, 0.10590551])

In [92]:
np.random.rand(5,5)

array([[0.6060473 , 0.08805266, 0.46940804, 0.29614602, 0.68838024],
       [0.91469531, 0.18140294, 0.02322721, 0.49239563, 0.79863989],
       [0.11247569, 0.51091699, 0.64136167, 0.03989059, 0.43963241],
       [0.98407481, 0.18785103, 0.54910079, 0.05371721, 0.6051552 ],
       [0.29057867, 0.32549038, 0.45830323, 0.61890596, 0.05062568]])

In [93]:
np.random.randn(2)

array([-1.07024174, -0.58099128])

In [94]:
np.random.randn(5,5)

array([[ 1.97693401, -0.33829848,  0.86659088, -1.20241493,  0.16302319],
       [ 0.08830325, -0.23915711, -1.51812356, -0.58256159,  0.43986113],
       [ 0.90373585,  1.82600606,  1.36890364,  1.12046886, -0.3946794 ],
       [ 1.42251164,  0.25827754, -0.81997468, -1.11765965, -0.63327229],
       [-0.78467073,  1.00021393, -0.76636316,  2.02266094,  0.41165009]])

In [95]:
np.random.randint(100)

44

In [96]:
arr=np.arange(0,25)
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [97]:
print(arr.max())

24


In [112]:
import pandas as pd
import numpy as np
lis=['sepal length in cm','sepal width in cm','petal length in cm','petal width in cm','class']
df=pd.read_csv('/Users/mayank/Downloads/Lab1-20221008/iris_data_with_missing_values.csv',names=lis)
print(df.index)

RangeIndex(start=0, stop=150, step=1)


In [113]:
df.head()

sepal length in cm  sepal width in cm  petal length in cm  \
0                 5.1                3.5                 1.4   
1                 4.9                3.0                 1.4   
2                 4.7                3.2                 1.3   
3                 4.6                3.1                 1.5   
4                 5.0                3.6                 1.4   

   petal width in cm        class  
0                0.2  Iris-setosa  
1                0.2  Iris-setosa  
2                0.2  Iris-setosa  
3                0.2  Iris-setosa  
4                0.2  Iris-setosa

In [114]:
df[0:20]

sepal length in cm  sepal width in cm  petal length in cm  \
0                  5.1                3.5                 1.4   
1                  4.9                3.0                 1.4   
2                  4.7                3.2                 1.3   
3                  4.6                3.1                 1.5   
4                  5.0                3.6                 1.4   
5                  5.4                3.9                 1.7   
6                  4.6                3.4                 1.4   
7                  5.0                3.4                10.0   
8                  4.4                2.9                 1.4   
9                  4.9                3.1                 1.5   
10                 5.4                3.7                 1.5   
11                 4.8                3.4                 1.6   
12                 4.8                3.0                 1.4   
13                 4.3                3.0                 1.1   
14                 5.8                4.0                 1.2   
15                 5.7                NaN                 1.5   
16                 5.4                3.9                 1.3   
17                 5.1                3.5                 1.4   
18                 5.7                3.8                 1.7   
19                 5.1                3.8                 1.5   

    petal width in cm        class  
0                 0.2  Iris-setosa  
1                 0.2  Iris-setosa  
2                 0.2  Iris-setosa  
3                 0.2  Iris-setosa  
4                 0.2  Iris-setosa  
5                 0.4  Iris-setosa  
6                 0.3  Iris-setosa  
7                 0.2  Iris-setosa  
8                 0.2  Iris-setosa  
9                 0.1  Iris-setosa  
10                0.2  Iris-setosa  
11                0.2  Iris-setosa  
12                0.1  Iris-setosa  
13                0.1  Iris-setosa  
14                0.2  Iris-setosa  
15                0.4  Iris-setosa  
16                0.4  Iris-setosa  
17                0.3  Iris-setosa  
18                0.3  Iris-setosa  
19                0.3  Iris-setosa

In [115]:
#Number of Zeroes
for i in df.columns:
    count_0=0
    for j in df[i]:
        if j==0:
            count_0=count_0+1
    print("{}  {}".format(i,count_0))

sepal length in cm  0
sepal width in cm  0
petal length in cm  0
petal width in cm  0
class  0


In [116]:
count_null=0

def count_nan():
    for i in df.columns:
        x=df[i].isna().sum()
    
        print("{} == {}".format(i,x))
count_nan()    

sepal length in cm == 3
sepal width in cm == 3
petal length in cm == 3
petal width in cm == 2
class == 3


In [117]:
#question 5
#replacing the 0 value with nan we are checking for both int as well as char
cols = ["sepal length in cm","sepal width in cm"]
df[cols] = df[cols].replace({'0':np.nan, 0:np.nan})

In [118]:
count_nan()

sepal length in cm == 3
sepal width in cm == 3
petal length in cm == 3
petal width in cm == 2
class == 3


In [119]:
df.isna().all(axis=1).sum()
df.isna().any(axis=1).sum()

13

In [120]:
df.dropna().count()

sepal length in cm    137
sepal width in cm     137
petal length in cm    137
petal width in cm     137
class                 137
dtype: int64

In [121]:
df.count()

sepal length in cm    147
sepal width in cm     147
petal length in cm    147
petal width in cm     148
class                 147
dtype: int64

In [122]:
df.dropna().count()

sepal length in cm    137
sepal width in cm     137
petal length in cm    137
petal width in cm     137
class                 137
dtype: int64

In [123]:
df.count()

sepal length in cm    147
sepal width in cm     147
petal length in cm    147
petal width in cm     148
class                 147
dtype: int64

In [124]:
#question 9
#filling the null values with mean 
#for class attribute we are filling the null value with mode
df['sepal length in cm'] = df['sepal length in cm'].fillna(df['sepal length in cm'].mean())
df['sepal width in cm'] = df['sepal width in cm'].fillna(df['sepal width in cm'].mean())
df['petal length in cm'] = df['petal length in cm'].fillna(df['petal length in cm'].mean())
df['petal width in cm'] = df['petal width in cm'].fillna(df['petal width in cm'].mean())
df['class'] = df['class'].fillna(df['class'].mode()[0])

In [125]:
df.count()

sepal length in cm    150
sepal width in cm     150
petal length in cm    150
petal width in cm     150
class                 150
dtype: int64

In [128]:
df1=pd.DataFrame(columns=lis)

In [129]:
df1.head()

Empty DataFrame
Columns: [sepal length in cm, sepal width in cm, petal length in cm, petal width in cm, class]
Index: []

In [130]:
df1=df

In [131]:
df1.head()

sepal length in cm  sepal width in cm  petal length in cm  \
0                 5.1                3.5                 1.4   
1                 4.9                3.0                 1.4   
2                 4.7                3.2                 1.3   
3                 4.6                3.1                 1.5   
4                 5.0                3.6                 1.4   

   petal width in cm        class  
0                0.2  Iris-setosa  
1                0.2  Iris-setosa  
2                0.2  Iris-setosa  
3                0.2  Iris-setosa  
4                0.2  Iris-setosa

In [133]:
#sampling the dataset
df_sample_replacement=df.sample(frac=.2,replace = True, random_state=2)
df_sample_nonreplacement=df.sample(frac=.2,replace=False,random_state=2)

In [134]:
# number of rows in the columns
df_sample_replacement.count()
df_sample_nonreplacement.count()

sepal length in cm    30
sepal width in cm     30
petal length in cm    30
petal width in cm     30
class                 30
dtype: int64

In [136]:
#zscore= (x-mean)/standarddeviation It is used to normalize the data
# question 12
#calculating the zscore and storing it in different columns
from scipy.stats import zscore
df['sepal_length_zscore'] = zscore(df['sepal length in cm'])
df['sepal_width_zscore'] = zscore(df['sepal width in cm'])
df['petal_length_zscore'] = zscore(df['petal length in cm'])
df['petal_width_zscore'] = zscore(df['petal width in cm'])

In [137]:
df.head()

sepal length in cm  sepal width in cm  petal length in cm  \
0                 5.1                3.5                 1.4   
1                 4.9                3.0                 1.4   
2                 4.7                3.2                 1.3   
3                 4.6                3.1                 1.5   
4                 5.0                3.6                 1.4   

   petal width in cm        class  sepal_length_zscore  sepal_width_zscore  \
0                0.2  Iris-setosa            -0.734506            0.298618   
1                0.2  Iris-setosa            -0.916125           -0.114723   
2                0.2  Iris-setosa            -1.097744            0.050613   
3                0.2  Iris-setosa            -1.188554           -0.032055   
4                0.2  Iris-setosa            -0.825316            0.381287   

   petal_length_zscore  petal_width_zscore  
0            -1.356197           -1.311334  
1            -1.356197           -1.311334  
2            -1.411853           -1.311334  
3            -1.300541           -1.311334  
4            -1.356197           -1.311334

In [ ]:
# for z score the z value> 3 is considerd as outliers
#question 13
#We identify outliers using zscore as if zscore value is greater than 3 that that value is outlier
(df['sepal_length_zscore']>3).sum()
(df['sepal_width_zscore']>3).sum()
(df['petal_length_zscore']>3).sum()
(df['petal_width_zscore']>3).sum()

In [138]:
(df['sepal_length_zscore']>3).sum()

1

In [139]:
(df['sepal_width_zscore']>3).sum()

1

In [140]:
(df['petal_length_zscore']>3).sum()


1

In [141]:
(df['petal_width_zscore']>3).sum()

0

In [142]:
# There are 1 outlier in three columns 

In [150]:
df1 = df[['sepal length in cm','sepal width in cm','petal length in cm','petal width in cm']]

In [151]:
# min max normalisation (x-min)/max-min
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

normalized_data = scaler.fit_transform(df1[1:4])

print(normalized_data)

[[1.         0.         0.5        0.        ]
 [0.33333333 1.         0.         0.        ]
 [0.         0.5        1.         0.        ]]


In [153]:
normalized_df = pd.DataFrame(normalized_data, columns=df1.columns)

print(normalized_df)


   sepal length in cm  sepal width in cm  petal length in cm  \
0            1.000000                0.0                 0.5   
1            0.333333                1.0                 0.0   
2            0.000000                0.5                 1.0   

   petal width in cm  
0                0.0  
1                0.0  
2                0.0  


In [154]:
#question 15
#creating 6 bins for storing the values of petal length column
pd.qcut(df['petal length in cm'], q=6)

0      (0.999, 1.5]
1      (0.999, 1.5]
2      (0.999, 1.5]
3      (0.999, 1.5]
4      (0.999, 1.5]
           ...     
145      (4.9, 5.6]
146      (4.9, 5.6]
147      (4.9, 5.6]
148      (4.9, 5.6]
149      (4.9, 5.6]
Name: petal length in cm, Length: 150, dtype: category
Categories (6, interval[float64, right]): [(0.999, 1.5] < (1.5, 3.433] < (3.433, 4.35] < (4.35, 4.9] < (4.9, 5.6] < (5.6, 10.0]]

In [155]:
#storing the petal length value in a data frame
df2 = pd.DataFrame(columns=['petal length in cm'])

In [156]:
#copying the values from the original data set
df2['petal length in cm']=df['petal length in cm']

In [157]:
# doing binning and storing the value in a column naming the bins based on length 
df2['petal length bin']=pd.cut(x=df2['petal length in cm'], bins=[0.999,1.5,3.433,4.35,4.9,5.6,10.0], 
                        labels=["very very short", "very short", "medium","tall","very tall",'tallest'])
print(df2.head())

   petal length in cm petal length bin
0                 1.4  very very short
1                 1.4  very very short
2                 1.3  very very short
3                 1.5  very very short
4                 1.4  very very short


In [158]:
#question 16
#calculating the pearsond correlation
from scipy.stats import pearsonr

In [159]:
df.corr()

sepal length in cm  sepal width in cm  \
sepal length in cm             1.000000          -0.045652   
sepal width in cm             -0.045652           1.000000   
petal length in cm             0.509271          -0.125489   
petal width in cm              0.518591          -0.109536   
sepal_length_zscore            1.000000          -0.045652   
sepal_width_zscore            -0.045652           1.000000   
petal_length_zscore            0.509271          -0.125489   
petal_width_zscore             0.518591          -0.109536   

                     petal length in cm  petal width in cm  \
sepal length in cm             0.509271           0.518591   
sepal width in cm             -0.125489          -0.109536   
petal length in cm             1.000000           0.873729   
petal width in cm              0.873729           1.000000   
sepal_length_zscore            0.509271           0.518591   
sepal_width_zscore            -0.125489          -0.109536   
petal_length_zscore            1.000000           0.873729   
petal_width_zscore             0.873729           1.000000   

                     sepal_length_zscore  sepal_width_zscore  \
sepal length in cm              1.000000           -0.045652   
sepal width in cm              -0.045652            1.000000   
petal length in cm              0.509271           -0.125489   
petal width in cm               0.518591           -0.109536   
sepal_length_zscore             1.000000           -0.045652   
sepal_width_zscore             -0.045652            1.000000   
petal_length_zscore             0.509271           -0.125489   
petal_width_zscore              0.518591           -0.109536   

                     petal_length_zscore  petal_width_zscore  
sepal length in cm              0.509271            0.518591  
sepal width in cm              -0.125489           -0.109536  
petal length in cm              1.000000            0.873729  
petal width in cm               0.873729            1.000000  
sepal_length_zscore             0.509271            0.518591  
sepal_width_zscore             -0.125489           -0.109536  
petal_length_zscore             1.000000            0.873729  
petal_width_zscore              0.873729            1.000000